### ISSUE TITLE
Restart and Refresh Features

### ISSUE THREAD

**Issue by dispherical** [javaarchive/OpenRadio#3]
In the Admin Panel, you said two features were coming soon, so I just wanted to show some suggestions:

Restart the server: `process.exit(1)`
Refresh Pages ([Source](https://gist.github.com/jchillerup/1603424)):

Client:
```
socket.on('reload', function (data) {
    location.reload();
});
```

Server: `io.sockets.emit('reload', {});`

**Comment by javaarchive** [comment]
Hi, thanks for the suggestions I'll defintley implement these by the next update after I finish up some high priority things
